export const info = [
  {
    number: 1,
    topic: "Depression Application",
    description: "Develop Web Application",
    time: "June 2021 - August 2021",
    info: [
      "Used Golang with Gin framework and REST API (using Postman for API test)",
      "Used Middleware for example, API authorization with JWT or JSON Web Token",
      "Used Compute Engine VM from GCP or Google Cloud Platform to deploy the web",
      "Used Speech-to-Text from GCP and Voice Activity Detection (VAD)",
      "Used docker as a container to wrap the website into it",
    ],
    link: "https://medium.com/@pawankanjeam/แชร์ประสบการณ์-ทำ-backend-web-application-project-ในเวลา-1-เดือน-ad1fd3c7e1a3",
    image: "https://source.unsplash.com/random/800x800",
  },
  {
    number: 2,
    topic: "Depression AI",
    description: "Built the model to predict depression scores",
    time: "September 2021 - November 2021",
    info: [
      "Labeled the data from DMH and fulfilled the dataset with ThaiSER, VISTEC dataset",
      "Used VAD to recognize voice activity and FFmpeg to slice the audio",
      "Used Efficientnet's model",
      "Used many important libraries ex. Pandas, Numpy, PyTorch, and TensorFlow",
    ],
    link: "https://medium.com/@pawankanjeam/แชร์ประสบการณ์ทำ-data-scientist-project-557e67832874",
    image: "https://source.unsplash.com/random/800x805",
  },
  {
    number: 3,
    topic: "D-Mind",
    description:
      "Developed the website to detect and monitor the prediction of depression for Chulalongkorn Hospital",
    time: "January 2022 - April 2022",
    info: [
      "Use ReactJS with Material UI to develop web application",
      "Use Axios library to make HTTP requests",
      "Use OOP concepts to develop reused UI components",
      "Work with the backend team to optimize existing API requests and create efficiencies by removing unneeded API requests",
      "Learnt the full-loop workflow of Web Development",
    ],
    link: "https://medium.com/@pawankanjeam/แชร์ประสบการณ์ทำ-frontend-web-application-project-980ed0fa0c7c",
    image: "https://source.unsplash.com/random/800x810",
  },
  {
    number: 4,
    topic: "This Website",
    description: "Developed this website",
    time: "March 2022 - Present",
    info: [
      "Use React.js + Matherial UI for frontend",
      "Use Golang + Gin for backend",
      "Use firebase for web hosting (will change soon)",
    ],
    link: "https://medium.com/@pawankanjeam/portfolio-7b6166e250c6",
    image: "https://source.unsplash.com/random/810x815",
  },
  {
    number: 5,
    topic: "Monster Brawl",
    description: "Developed the 2D local-multiplayer game",
    time: "January 2021 - May 2021",
    info: [
      "Used Java with JavaFX to develop this game",
      "Used OOP concepts to develop and reuse the object of characters or the players",
      "Learnt how to use thread and timer",
    ],
    link: "https://medium.com/@pawankanjeam/แชร์ประสบการณ์ทำ-game-ด้วย-javafx-9814f40070ca",
    image: "https://source.unsplash.com/random/800x815",
  },
  {
    number: 6,
    topic: "Cute Queue",
    description: "Developed the website that uses for queue management",
    time: "April 2022 - May 2022",
    info: [
      "Used React.js + TailwindCSS",
      "Used firebase as an API endpoint and Web hosting",
      "Learnt how to use STM32 and ESP32 (using Arduino IDE)",
    ],
    link: "https://medium.com/@pawankanjeam/portfolio-7b6166e250c6",
    image: "https://source.unsplash.com/random/805x815",
  },
  {
    number: 7,
    topic: "Meme Web Application",
    description: "Developed the website that uses for sharing or finding memes",
    time: "January 2021 - May 2021",
    info: [
      "Used basic HTML, CSS, and JavaScript to develop",
      "Used firebase as an API endpoint and Web hosting",
    ],
    link: "https://medium.com/@pawankanjeam/แชร์ประสบการณ์ทำ-frontend-web-application-project-meme-2b7347dc8c69",
    image: "https://source.unsplash.com/random/805x825",
  },
];
